apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: experiment-run
spec:
  serviceAccountName: helm-installer
  taskRef:
    name: experiment
  params:
    - name: namespace
      value: kalantar
    - name: model-id
      value: "Qwen/Qwen3-0.6B"
    - name: experimentBaseUrl
      value: https://raw.githubusercontent.com/kalantar/llm-d-benchmark/refs/heads/tekton-poc/tekton-poc/examples/inference-scheduling/
    - name: harnessProfile
      value: shared_prefix_synthetic.yaml

    - name: gaiePluginConfig
      value: "inf-sche-queue.yaml"
    - name: question_len
      value: 100
    - name: output_len
      value: 300

