apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: experiment-matrix-run
spec:
  taskRunTemplate:
    serviceAccountName: helm-installer
  workspaces:
    - name: data
      persistentVolumeClaim:
        claimName: workspace-pvc
  pipelineSpec:
    workspaces:
      - name: data
    tasks:
      - name: run-experiment
        taskRef:
          name: experiment
        workspaces:
          - name: data
            workspace: data
        params:
          - name: namespace
            value: kalantar
          - name: model-id
            value: "Qwen/Qwen3-0.6B"
          - name: experimentBaseUrl
            value: https://raw.githubusercontent.com/kalantar/llm-d-benchmark/refs/heads/tekton-poc/tekton-poc/examples/inference-scheduling/
          - name: harnessProfile
            value: shared_prefix_synthetic.yaml
        matrix:
          params:
            - name: gaiePluginConfig
              value: 
                - "inf-sche-none.yaml"
                - "inf-sche-prefix.yaml"
                - "inf-sche-kv.yaml"
                - "inf-sche-queue.yaml"
            - name: question_len
              value:
                - "100"
                - "300"
                - "1000"
            - name: output_len
              value: 
                - "100"
                - "300"
                - "1000"
          include:
            - name: combo-1
              params:
                - name: gaiePluginConfig
                  value: "inf-sche-none.yaml"
                - name: question_len
                  value: "100"
                - name: output_len
                  value: "100"
            - name: combo-2
              params:
                - name: gaiePluginConfig
                  value: "inf-sche-prefix.yaml"
                - name: question_len
                  value: "300"
                - name: output_len
                  value: "300"
            - name: combo-3
              params:
                - name: gaiePluginConfig
                  value: "inf-sche-kv.yaml"
                - name: question_len
                  value: "1000"
                - name: output_len
                  value: "100"
            - name: combo-4
              params:
                - name: gaiePluginConfig
                  value: "inf-sche-queue.yaml"
                - name: question_len
                  value: "300"
                - name: output_len
                  value: "1000"