apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: experiment-matrix-run
spec:
  taskRunTemplate:
    serviceAccountName: helm-installer
  workspaces:
    - name: data
      persistentVolumeClaim:
        claimName: workspace-pvc
  pipelineSpec:
    workspaces:
      - name: data
    tasks:
      - name: run-experiment
        taskRef:
          name: experiment
        workspaces:
          - name: data
            workspace: data
        params:
          - name: namespace
            value: jchen
          - name: model-id
            value: "Qwen/Qwen3-0.6B"
          - name: experimentBaseUrl
            value: https://raw.githubusercontent.com/jgchn/llm-d-benchmark/refs/heads/jc-tekton/tekton-poc/examples/inference-scheduling/
          - name: harnessProfile
            value: shared_prefix_synthetic_short.yaml
          - name: pipelineUID
            value: "$(context.pipelineRun.uid)"
        matrix:
          params:
            - name: gaiePluginConfig
              value:
                - "inf-sche-upstream-default.yaml"
                - "inf-sche-load.yaml"
            - name: question_len
              value:
                - "100"
                - "300"
                - "1000"
            - name: output_len
              value:
                - "100"
                - "300"
                - "1000"
