apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: experiment-matrix-run
spec:
  taskRunTemplate:
    serviceAccountName: helm-installer
  pipelineSpec:
    tasks:
      - name: run-experiment
        taskRef:
          name: experiment
        params:
          - name: namespace
            value: CHANGE_ME
          - name: model-id
            value: "Qwen/Qwen3-0.6B"
          - name: experimentBaseUrl
            value: https://raw.githubusercontent.com/kalantar/llm-d-benchmark/refs/heads/tekton-poc/tekton-poc/examples/inference-scheduling/
          - name: harnessProfile
            value: shared_prefix_synthetic.yaml
        matrix:
          params:
            - name: gaiePluginConfig
              value: 
                - "inf-sche-none.yaml"
                - "inf-sche-prefix.yaml"
                - "inf-sche-kv.yaml"
                - "inf-sche-queue.yaml"
            - name: question_len
              value:
                - "100"
                - "300"
                - "1000"
            - name: output_len
              value: 
                - "100"
                - "300"
                - "1000"
