# Sample EPP configuration for running without P/D with prefix scorer with weight of 1

apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: EndpointPickerConfig
plugins:
- type: decode-filter
- type: max-score-picker
- type: single-profile-handler
- type: prefix-cache-scorer
- type: load-aware-scorer
  parameters:
    threshold: 1
schedulingProfiles:
- name: default
  plugins:
  - pluginRef: decode-filter
  - pluginRef: max-score-picker
  - pluginRef: prefix-cache-scorer
    weight: 1
  - pluginRef: load-aware-scorer
    weight: 1